name: CI

on:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  workflow_dispatch:

jobs:
  GNU:
    runs-on: ubuntu-latest
    
    env:
      FC: gfortran
      PFUNIT_DIR: /home/runner/work/Fortran-Unit-Test-Basic/Fortran-Unit-Test-Basic/pFUnit/build/installed/PFUNIT-4.9
    
    name: gfortran
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install lcov
        run: |
          sudo apt install lcov
          # sudo apt install openmpi-bin
        
      - name: Install pFUnit
        run: |
          git clone https://github.com/Goddard-Fortran-Ecosystem/pFUnit
          cd pFUnit
          mkdir -p build
          cd build
          cmake ..
          make -j$(nproc)
          make tests
          make install
          
      - name: Run script (build, tests, coverage)
        run: |
          ./build_gfortran.sh
          
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report-gfortran
          path: build/coverage/
  
  Intel:
    runs-on: ubuntu-latest
    
    env:
      FC: ifx
      CC: icx
      PFUNIT_DIR: /home/runner/work/Fortran-Unit-Test-Basic/Fortran-Unit-Test-Basic/pFUnit/build/installed/PFUNIT-4.9
    
    name: Intel Fortran
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Taken from https://gist.github.com/scivision/d94bb10a01fa3b8ed0c9a93ee16318ba
      - name: Intel Apt repository
        timeout-minutes: 1
        run: |
          wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
          sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
          rm GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
          echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update
        
      - name: Install Intel oneAPI compilers
        timeout-minutes: 5
        run: sudo apt-get install intel-oneapi-compiler-fortran intel-oneapi-compiler-dpcpp-cpp 

      # optional
      #- name: Install Intel MPI and MKL
      #  timeout-minutes: 5
      #  run: intel-oneapi-mpi intel-oneapi-mpi-devel intel-oneapi-mkl

      - name: Setup Intel oneAPI environment
        run: |
          source /opt/intel/oneapi/setvars.sh
          printenv >> $GITHUB_ENV
      
      - name: Versions
        run: |
          ${FC} --version
          ${CC} --version
          
      - name: Install pFUnit
        run: |
          git clone https://github.com/Goddard-Fortran-Ecosystem/pFUnit
          cd pFUnit
          mkdir -p build
          cd build
          cmake ..
          make -j$(nproc)
          make tests
          make install
          
      - name: Run script (build, tests, coverage)
        run: |
          ./build_ifort.sh
          
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report-ifort
          path: build/tests/coverage/
